# Generated by Django 2.1.5 on 2021-08-04 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_page_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
