# Generated by Django 2.1.5 on 2021-08-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
