# Generated by Django 2.1.5 on 2021-08-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_auto_20210804_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_title',
            new_name='title',
        ),
    ]
