# Generated by Django 2.1.5 on 2021-08-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_remove_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
