# Generated by Django 2.1.5 on 2021-08-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20210804_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='categoryID',
            field=models.IntegerField(default=0),
        ),
    ]
