# Generated by Django 2.1.5 on 2021-08-05 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_news_categoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
