# Generated by Django 2.1.5 on 2021-08-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_likepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='newsID',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='pageID',
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.CharField(default='hhhh', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='page',
            field=models.CharField(default='aaaaa', max_length=256),
            preserve_default=False,
        ),
    ]
